server:
  address:::
  port: 8001
  # -Djava.net.preferIPv6Addresses=true

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level - %msg%n"
  file:
    path: ./logs  # 指定日志目录为当前目录下的logs文件夹
    name: ./logs/out.log  # 主日志文件路径
  logback:
    rollingpolicy:
      max-file-size: 100MB
      file-name-pattern: ./logs/%d{yyyyMMdd}%i.log
      max-history: 30
      total-size-cap: 10GB

llm:
  ollama:
    url: http://127.0.0.1:7099
#    model: deepseek-r1:14b
    model: qwen3:8b

  deepseek:
    url: https://api.deepseek.com/v1
    model: deepseek-chat
    appkey: sk-dd3d139eb5de423fa118300e7b2d7e82

jdbc:
  sources:
    - url: jdbc:mysql://192.168.1.110:3306/mydb?
      username: root
      password: '000000'

wx:
  minprog:
    appid: wx9b378439484b1ad2
    appsecret: bbbb7659c28f354679476e32aa14ce62



